---
run:
  # If it is explicitly set to 0 (i.e. not the default) then golangci-lint will automatically set the value to match Linux container CPU quota.
  concurrency: 0
  timeout: 5m
  issues-exit-code: 2
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable-all: false
  enable-all: true
  disable:
    # I like namedreturns occasionally
    - nonamedreturns
    # Deprecated
    - exportloopref
    # Too annoying
    - exhaustruct  # this is fine without, usually
    - funlen  # somewhat ridiculous
    - cyclop  # who cares! :D
    - godox  # just leave it alone
    # TODO(apostasie) Temporary out until we wrap up all of them
    - wrapcheck

    # We us go-imports instead
    - gci

    # To be enabled
    - intrange
    - copyloopvar
    - wsl
    - nlreturn
    - gochecknoglobals
    - godot
    - lll
    - varnamelen
    - thelper
    - protogetter
    - gosec
    - err113
    - gofumpt
    - exhaustive
    - musttag
    - paralleltest
    - testpackage
    - nestif
    - contextcheck
    - gocyclo
    - forcetypeassert
    - gocognit
    - errcheck
    - dupl
    - whitespace
    - mnd
    - ireturn
    - nilnil
    - tparallel
    - tagliatelle
    - goconst
    - maintidx

linters-settings:
  gocritic:
    disabled-checks:
      - appendAssign
      - ifElseChain

  depguard:
    rules:
      main:
        files:
          - "$all"
          - "!**/leptonic/**/*"
        # list-mode: strict
        deny:
          - pkg: "github.com/hashicorp/golang-lru"
            desc: "Do not allow direct use of IBM patented NewARC"
          - pkg: "github.com/sirupsen/logrus"
            desc: "we use Zerolog"
          - pkg: "github.com/bugsnag/bugsnag-go"
            desc: "we use Sentry"
          - pkg: "github.com/pkg/errors"
            desc: "should be replaced by standard lib errors package"
          - pkg: "github.com/opencontainers"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/cgroups"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/containerd/v2/contrib/apparmor"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/containerd/containerd/v2/contrib/seccomp"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/distribution"
            desc: "use farcloser containers library instead"
          - pkg: "github.com/fluent"
            desc: "use farcloser containers library instead"
          # - pkg: "github.com/vishvananda"

      pkg:
        files:
          - "**/pkg/**/*.go"
        deny:
          - pkg: "github.com/spf13"
            desc: "pkg must not depend on cobra or pflag"
          - pkg: "github.com/containerd/nerdctl/v2/cmd"
            desc: "pkg must not depend on cmd files"

issues:
  exclude-rules:
    - linters:
        - revive
      text: "unused-parameter"
