name: build

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  SHORT_TIMEOUT: 5
  LONG_TIMEOUT: 60

jobs:
  build:
    timeout-minutes: 5
    name: ${{ matrix.go-version }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        go-version: ["1.23", "1.24"]
    steps:
      - name: "Clone"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: "Install go"
        uses: ./.github/actions/install-go
        with:
          version: ${{ matrix.go-version }}
      - name: "build"
        run: make binaries
