name: lint

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  go-current:
    name: "go stable"
    timeout-minutes: 5
    uses: ./.github/action/node
    with:
      depth: 100
    steps:
      - name: lint
        run: |
          export LINT_COMMIT_RANGE="$(jq -r '.after + "..HEAD"' ${GITHUB_EVENT_PATH})"
          make lint

  go-canary:
    timeout-minutes: 5
    name: "go canary"
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout project, 100 commits"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 100
      - name: "Install go"
        uses: ./.github/actions/install-go
        with:
          version: canary
      - name: "Install dev-tools"
        uses: ./.github/actions/install-dev-tools

      - name: lint
        run: |
          export LINT_COMMIT_RANGE="$(jq -r '.after + "..HEAD"' ${GITHUB_EVENT_PATH})"
          make lint
