name: lint

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  lint:
    timeout-minutes: 5
    name: "${{ matrix.goos }} | ${{ matrix.goversion }}"
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            goos: linux
            goversion: latest-stable
          - os: ubuntu-24.04
            goos: windows
            goversion: latest-stable
          - os: ubuntu-24.04
            goos: linux
            goversion: canary
    steps:
      - name: "Checkout project, 100 commits"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 100
      - name: "Install golang"
        uses: ./.github/actions/install-go
        with:
          strategy: ${{ matrix.goversion }}
      - name: "Install golangci"
        run: |
          echo "::group:: make lint-install-golangci"
          make lint-install-golangci
          echo "::endgroup::"
      - name: "`make lint-go`"
        env:
          VERBOSE: true
          GOOS: ${{ matrix.goos }}
        run: |
          make lint-go
      - name: "Other linters"
        # These are not influenced by GOOS - running them multiple times is thus unnecessary
        if: ${{ matrix.goos=='linux' &&  matrix.goversion=='latest-stable' }}
        run: |
          export LINT_COMMIT_RANGE="$(jq -r '.after + "..HEAD"' ${GITHUB_EVENT_PATH})"

          make lint-install-tools

          make lint-imports
          make lint-headers
          make lint-commits
          make lint-licenses-all

          make lint-mod

          make lint-yaml
          make lint-shell
