name: test-docker

on:
  push:
    branches:
      - main
      - 'release/**'
  # Only trigger on PRs if we changed a test file, or any of the test rig or actions assets
  pull_request:
    paths:
      - '**_test.go'
      - '**.sh'
      - '**.toml'
      - '**.conf'
      - '**.service'
      - '**.yml'

env:
  SHORT_TIMEOUT: 5
  LONG_TIMEOUT: 60

jobs:
  test-integration-docker-compatibility:
    timeout-minutes: 30
    name: docker
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 1
      - name: "Install go"
        uses: ./.github/actions/install-go
      - name: "Register QEMU (tonistiigi/binfmt)"
        run: |
          # `--install all` will only install emulation for architectures that cannot be natively executed
          # Since some arm64 platforms do provide native fallback execution for 32 bits,
          # armv7 emulation may or may not be installed, causing variance in the result of `uname -m`.
          # To avoid that, we explicitly list the architectures we do want emulation for.
          docker run --privileged --rm tonistiigi/binfmt --install linux/amd64
          docker run --privileged --rm tonistiigi/binfmt --install linux/arm64
          docker run --privileged --rm tonistiigi/binfmt --install linux/arm/v7
      - name: "Prepare integration test environment"
        run: |
          sudo apt-get install -y expect
          go install -v gotest.tools/gotestsum@v1
      - name: "Ensure that the integration test suite is compatible with Docker"
        run: WITH_SUDO=true ./hack/test-integration.sh -test.target=docker
      - name: "Ensure that the IPv6 integration test suite is compatible with Docker"
        run: WITH_SUDO=true ./hack/test-integration.sh -test.target=docker -test.only-ipv6
      - name: "Ensure that the integration test suite is compatible with Docker (flaky only)"
        run: WITH_SUDO=true ./hack/test-integration.sh -test.target=docker -test.only-flaky
